steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['clean','install', '-Dmaven.test.skip=true']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/virtualan-mock:1.0.$BUILD_ID', '.']
  timeout: 180s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/virtualan-mock:1.0.$BUILD_ID']
  # Deploy an image from Container Registry to Cloud Run
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'deploy.yaml' ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
