apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-service
spec:
  selector:
    matchLabels:
      app: virtualan-mock
      env: dev
  replicas: 3
  template:
    metadata:
      labels:
        app: virtualan-mock
        env: dev
    spec:
      containers:
        - name: virtualan
          image: "gcr.io/erudite-scarab-284417/virtualan-mock:1.0"
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: virtualan-cmap
            items:
            - key: "application.properties"
              path: "application.properties"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: virtualan-cmap
  namespace: default
data:
  application.properties: |
    server.port=8080
    virtualan.datasource.driver-class-name=org.hsqldb.jdbcDriver
    virtualan.datasource.jdbcurl=jdbc:hsqldb:mem:dataSource
    virtualan.datasource.username=sa
    virtualan.datasource.password=
    virtualan.application.name=TEST for Product
    virtualan.data.load=initial-load.json
---
apiVersion: v1
kind: Service
metadata:
  name: mock-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: virtualan-mock
    env: dev
